### ISSUE TITLE
how to train your model?

### ISSUE THREAD

**Issue by xiaojidan** [limuhit/ImageCompression#1]
Hi @limuhit  Can you share me the training codes  for further work? I am interested in them

**Comment by limuhit** [comment]
Sorry, it is not convenient to share the source code with you. We are currently cooperating with Huawei for image compression with the codes. The opened the part is only for the test and show the results of the paper.

**Comment by Lelouch422** [comment]
Hi, @limuhit, I failed to download the pycaffe package in Google Drive, could you please upload it in Baidu NetDisk or somewhere else. Thanks a lot!
