### ISSUE TITLE
关于环境的问题？

### ISSUE THREAD

**Issue by a1103688841** [limuhit/ImageCompression#4]
你好！您在上面写的环境是win10,vs2015,cuda8，请问我可以使用ubuntu16.04,gcc5.4.0,cuda10实现吗？？在import caffe的时候出现No module named _caffe 到现在我并未解决。

**Comment by limuhit** [comment]
You need to recompile the codes on ubuntu with your own environment.  However, we had cooperation with Huawei and promise to not share the codes. You may try our new job which has the caffe source code available on GitHub.  The link is https://github.com/limuhit/SCAE.

**Comment by a1103688841** [comment]
哦哦 好的 谢谢老师指导

**Comment by nanfangyuan** [comment]
老师 有tensorflow 版本的源码可以学习吗

**Comment by AkeLiLi** [comment]
> 哦哦 好的 谢谢老师指导

请问你的问题解决了么，我遇到了和你一样的问题
