### ISSUE TITLE
关于 Caffee 的问题

### ISSUE THREAD

**Issue by aalex1945** [limuhit/ImageCompression#7]
您好，您提供个的 google drive 上面的 Caffe 只能用于 Windows 10，而且一定要注册后才能下载。请问有什么别的下载渠道吗？另外，修改后的 Caffe 没有公开源代码，这使得在 Ubuntu 上部署存在困难。请问可以使用原版的 Caffe 吗？或者是可以给出修改后的代码吗？谢谢。

**Comment by limuhit** [comment]
There is an implementation of the importance map at https://github.com/limuhit/360-Image-Compression.

**Comment by aalex1945** [comment]
@limuhit  Thank you !!
